### ISSUE TITLE
内置配置 ipv6 格式错误导致无法启动

### ISSUE THREAD

**Issue by ichenhe** [sbwml/luci-app-mosdns#107]
环境：

- x86_64 路由器
- iStoreOS 22.03.4 2023071416 （官方称完全兼容 openwrt 未魔改）
- 已获取公网 ipv6 与前缀
- 清洁安装

执行 `mosdns start -c /etc/mosdns/config.yaml` 启动报错：

```
Error: fail to load config, failed to read config: While parsing config: yaml: line 89: mapping values are not allowed in this context
2023-07-23T14:43:43.171Z	FATAL	fail to load config, failed to read config: While parsing config: yaml: line 89: mapping values are not allowed in this context
```

对应配置文件 89 行：

```yaml
  - tag: forward_local
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: 119.29.29.29
        - addr: 2402:4e00::   # <----------------- line 89
```

这一行应该这么写：

```yaml
 - addr: '[2402:4e00::]'
```
