### ISSUE TITLE
Mosdns 5.2.1做了什么调整吗？

### ISSUE THREAD

**Issue by daiyou519** [sbwml/luci-app-mosdns#146]
一直用Mosdns加Openclash防dns泄漏,设置参照的是：[https://www.right.com.cn/forum/thread-8293938-1-1.html](url)，之前一直用Mosdns v5.1.3,昨天更新5.2.1后，其它设置不变而dns发生泄漏，是哪里的问题，请问该如何设置？

**Comment by sbwml** [comment]
谢谢反馈，和 mosdns 版本的升级无关，排查了一下配置文件，是由 https://github.com/sbwml/luci-app-mosdns/commit/476d0bf24ff88d3bd230066104d49d4f2bb405c3 引起，晚些时候我会修复它

**Comment by sbwml** [comment]
已修复：https://github.com/sbwml/luci-app-mosdns/commit/9bb28a32d38613df05f13c9b9f243e46d9e734fd

**Comment by yyysuo** [comment]
手工修改了/etc/init.d/mosdns，测试还是泄露呢。

**Comment by dsyo2008** [comment]
泄露了。。。只能退回5号正常了

**Comment by RavenCage** [comment]
额嗯，硬路由，软路由都有泄漏，等待新版本，重新生成固件估计就行了。

**Comment by sbwml** [comment]
**防止 DNS 泄漏  ✅  -  启用此选项 fallback 策略会强制转发到远程 DNS**

这个选项在 476d0bf24ff88d3bd230066104d49d4f2bb405c3 commit 确实出现了失效的情况，原因是：原 `query_is_local_ip` tag name 变为 `query_is_non_local_ip` ，而 init.d 配置生成脚本未同步做处理导致。

最新 commit https://github.com/sbwml/luci-app-mosdns/commit/9bb28a32d38613df05f13c9b9f243e46d9e734fd 之后，在 https://browserleaks.com/dns 测试中已经不再复现泄露问题。

**Comment by sbwml** [comment]
在 https://github.com/sbwml/luci-app-mosdns/releases 下载的 ipk 中，“防止 DNS 泄漏 ” 泄露选项是工作的，因为 releases 中的 ipk 包它不是最新源码。

如果你是直接编译到固件的，那么你需要重新拉取最新的 luci-app-mosdns 源码重新编译。

**Comment by dsyo2008** [comment]
哦只能编译固件更新有效？我编译插件后更新插件不行吗？

**Comment by yyysuo** [comment]
> 在 https://github.com/sbwml/luci-app-mosdns/releases 下载的 ipk 中，“防止 DNS 泄漏 ” 泄露选项是工作的，因为 releases 中的 ipk 包它不是最新源码。
> 
> 如果你是直接编译到固件的，那么你需要重新拉取最新的 luci-app-mosdns 源码重新编译。

我对照着您修改记录中的修改项，直接把本地的配置模板及mosdns.sh给替换了，luci网页中的修改不知道怎么改，但是我觉得应该没影响吧，最后在luci中重新应用了配置，生成的配置文件应该是对的吧，但是重新测试泄露，还是会泄露的；
重新安装了releases中的最新版本，是没有泄露的。

我用的是：https://www.astrill.com/zh/dns-leak-test

大佬有时间重新编译个最新版本呗，我原来fork一下就能自己编译，最近不知道github做了什么调整，没办法自己编译了。

**Comment by sbwml** [comment]
> 哦只能编译固件更新有效？我编译插件后更新插件不行吗？

去更新一个固件已经存在的插件，你得改变 makefile 的版本号才能正确更新

**Comment by yyysuo** [comment]
重新测试了一下：https://www.astrill.com/zh/dns-leak-test
安装releases的最新版本。
下载最新源码中的default.yaml和mosdns，覆盖/usr/share/mosdns的模板文件和/etc/ini.d中的脚本。
luci中重新应用。
最后还是泄露。
重新安装releases的最新版本不会泄露。

**Comment by RavenCage** [comment]
最新的release在哪儿？我看都是三周前的ipk啊。

**Comment by qingtian110** [comment]
拉最新源码编译出来的   没有问题    只检测到 Google LLC 一个供应商

![image](https://github.com/sbwml/luci-app-mosdns/assets/87856890/601d44d1-33ec-47e1-ad2d-90f103a42629)

**Comment by yyysuo** [comment]
> 拉最新源码编译出来的 没有问题 只检测到 Google LLC 一个供应商
> 
> ![image](https://user-images.githubusercontent.com/87856890/275482445-601d44d1-33ec-47e1-ad2d-90f103a42629.png)

求ipk

**Comment by dsyo2008** [comment]
> 拉最新源码编译出来的 没有问题 只检测到 Google LLC 一个供应商
> 
> ![image](https://user-images.githubusercontent.com/87856890/275482445-601d44d1-33ec-47e1-ad2d-90f103a42629.png)

更新插件还是重刷固件？

**Comment by sbwml** [comment]
> 最新的release在哪儿？我看都是三周前的ipk啊。

直接用三周前的 ipk 就行。这个泄露问题只出现在通过源码自己编译的情况下出现，这种情况只能再次重新编译。

release 发布的版本不受影响

**Comment by qingtian110** [comment]
> 求ipk

有 ipk，但是我用 sdk 编译出来的，它只能安装到 openwrt-23.05 固件上。github 不支持发送 .ipk 附件。。。。

**Comment by qingtian110** [comment]
这个，最新插件源码编译的

[luci-app-mosdns_1.5.12_all.zip](https://github.com/sbwml/luci-app-mosdns/files/12915603/luci-app-mosdns_1.5.12_all.zip)

**Comment by yyysuo** [comment]
> 这个，最新插件源码编译的
> 
> [luci-app-mosdns_1.5.12_all.zip](https://github.com/sbwml/luci-app-mosdns/files/12915603/luci-app-mosdns_1.5.12_all.zip)

奇怪，我测试是有泄露的。

**Comment by qingtian110** [comment]
> > 这个，最新插件源码编译的
> > [luci-app-mosdns_1.5.12_all.zip](https://github.com/sbwml/luci-app-mosdns/files/12915603/luci-app-mosdns_1.5.12_all.zip)
> 
> 奇怪，我测试是有泄露的。

你有缓存吧，或者做了套娃之类啥的

**Comment by qingtian110** [comment]
或者你根本没有更新到 ipk，就像大佬说的

> 去更新一个固件已经存在的插件，你得改变 makefile 的版本号才能正确更新

相同版本的号的  ipk 文件是没法“更新” 的。除非卸载后安装

**Comment by yyysuo** [comment]
> 或者你根本没有更新到 ipk，就像大佬说的
> 
> > 去更新一个固件已经存在的插件，你得改变 makefile 的版本号才能正确更新
> 
> 相同版本的号的 ipk 文件是没法“更新” 的。除非卸载后安装

opkg install luci-app-mosdns_1.5.12_all.ipk --force-reinstall
这样是可以的，我在你的版本和sbwml大佬发布的版本之间切换是没问题的。
套娃是有，但是2个版本之间完全相同的配置，sbwml的发布版本不漏，最新源码会漏。

**Comment by qingtian110** [comment]
配置文件呢？你把你的 /etc/mosdns/config.yaml 文件内容贴出来看看

**Comment by qingtian110** [comment]
如果配置文件的  fallback，两项都是 `forward_remote_upstream` 的话，就可以说明不是 mosdns 的问题。得从别的地方找找原因

```yaml
  - tag: fallback
    type: fallback
    args:
      primary: forward_remote_upstream
      secondary: forward_remote_upstream
      threshold: 500
      always_standby: true
```

**Comment by yyysuo** [comment]
> 如果配置文件的 fallback，两项都是 `forward_remote_upstream` 的话，就可以说明不是 mosdns 的问题。得从别的地方找找原因
> 
> ```yaml
>   - tag: fallback
>     type: fallback
>     args:
>       primary: forward_remote_upstream
>       secondary: forward_remote_upstream
>       threshold: 500
>       always_standby: true
> ```

大佬的模板是这样的啊，在源码中可以看到：
https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/default.yaml

  - tag: fallback
    type: fallback
    args:
      primary: query_is_non_local_ip
      secondary: forward_remote_upstream
      threshold: 500
      always_standby: true

**Comment by redfrog999** [comment]
> > 最新的release在哪儿？我看都是三周前的ipk啊。
> 
> 直接用三周前的 ipk 就行。这个泄露问题只出现在通过源码自己编译的情况下出现，这种情况只能再次重新编译。
> 
> release 发布的版本不受影响

非常感谢，那我开始编译了。

**Comment by qingtian110** [comment]
> 大佬的模板是这样的啊，在源码中可以看到：
> 
> * tag: fallback
>   type: fallback
>   args:
>   primary: query_is_non_local_ip
>   secondary: forward_remote_upstream
>   threshold: 500
>   always_standby: true

靠   看你路由器实际的配置文件，源码的那个 default.yaml 模板看他没用。luci 是根据设置去改写这个模板最后生成新的  /etc/mosdns/config.yaml ，最终是什么效果全看  /etc/mosdns/config.yaml

**Comment by qingtian110** [comment]
luci 上不是有说明吗    **启用此选项 fallback 策略会强制转发到远程 DNS**   （ 打开luci 这个开关后    fallback 策略才会强制    不然就是默认模板的方式    国内、国外同时查域名，所以才会有“泄露” 的叫法。

我看你挺迷糊的，自己研究研究

**Comment by yyysuo** [comment]
> > 大佬的模板是这样的啊，在源码中可以看到：
> > 
> > * tag: fallback
> >   type: fallback
> >   args:
> >   primary: query_is_non_local_ip
> >   secondary: forward_remote_upstream
> >   threshold: 500
> >   always_standby: true
> 
> 靠 看你路由器实际的配置文件，源码的那个 default.yaml 模板看他没用。luci 是根据设置去改写这个模板最后生成新的 /etc/mosdns/config.yaml ，最终是什么效果全看 /etc/mosdns/config.yaml

没迷糊啊，对于这个选项我还是有点了解的，防泄露的按钮就是我求sbmwl加上的，原来都是自己改配置文件。
我安装了你上传的最新的版本，在luci中重新应用生成的配置，配置文件不太对。
```yaml
log:
  level: info
  file: "/tmp/mosdns.log"

api:
  http: "0.0.0.0:9091"

include: []

plugins:
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  - tag: geosite_apple
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_apple.txt"

  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  - tag: whitelist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/whitelist.txt"

  - tag: blocklist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklist.txt"

  - tag: greylist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"

  - tag: ddnslist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/ddnslist.txt"

  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

  - tag: redirect
    type: redirect
    args:
      files:
        - "/etc/mosdns/rule/redirect.txt"

  - tag: adlist
    type: domain_set
    args:
      files:
        - "/var/disable-ads.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/local-ptr.txt"

  - tag: cloudflare_cidr
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/cloudflare-cidr.txt"

  - tag: lazy_cache
    type: cache
    args:
      size: 0
      lazy_cache_ttl: 0

  - tag: forward_xinfeng_udp
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "114.114.114.114"
        - addr: "114.114.115.115"

  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "127.0.0.1:8055"
          bootstrap: 223.5.5.5
          enable_pipeline: false
          max_conns: 2
          insecure_skip_verify: false
          idle_timeout: 30

  - tag: forward_remote
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "10.10.10.4:7874"
          bootstrap: 223.5.5.5
          enable_pipeline: false
          max_conns: 2
          insecure_skip_verify: false
          idle_timeout: 30

  - tag: forward_remote_upstream
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 0-0

  - tag: modify_ddns_ttl
    type: sequence
    args:
      - exec: ttl 5-5

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $modify_ddns_ttl
      - matches: "!qname $ddnslist"
        exec: $modify_ttl
      - matches: has_resp
        exec: accept

  - tag: query_is_non_local_ip
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  - tag: fallback
    type: fallback
    args:
      primary: query_is_non_local_ip
      secondary: forward_remote_upstream
      threshold: 500
      always_standby: true

  - tag: apple_domain_fallback
    type: fallback
    args:
      primary: query_is_non_local_ip
      secondary: forward_xinfeng_udp
      threshold: 100
      always_standby: true

  - tag: query_is_apple_domain
    type: sequence
    args:
      - matches: "!qname $geosite_apple"
        exec: return
      - exec: $apple_domain_fallback

  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $forward_local

  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $forward_local

  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $forward_remote_upstream

  - tag: query_is_whitelist_domain
    type: sequence
    args:
      - matches: qname $whitelist
        exec: $forward_local

  - tag: query_is_greylist_domain
    type: sequence
    args:
      - matches: qname $greylist
        exec: $forward_remote_upstream

  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches: qname $blocklist
        exec: reject 3
      - matches: qname $adlist
        exec: reject 3
      - matches:
        - qtype 12
        - qname $local_ptr
        exec: reject 3
      - matches: qtype 65
        exec: reject 3

  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5454"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5454"
```
