### ISSUE TITLE
在内置预设的情况下，能不能将某个域名解析道指定的内网IP？

### ISSUE THREAD

**Issue by nukewarrior** [sbwml/luci-app-mosdns#148]
在smartdns里，可以通过`address /my.domain.top/192.168.3.33`将**my.domain.top**解析道内网IP**192.168.3.33**上，这样局域网内访问域名可以直达对应内网服务器。
不知道mosdns需要如何配置完成类似的需求，谢谢🙏

我知道在`规则列表` - `Hosts`里可以针对每条域名单独设置，但是子域名多的话维护就很麻烦了。

**Comment by sbwml** [comment]
内置预设 只能通过 Host 来实现。

如果你希望是这个域名的所有子域都应答指定IP，你只能通过自定义配置编写规则去实现。

自定义配置思路：

```yaml
  - tag: ""
    type: sequence
    args:
      - matches: "qname domain:domain.top"
        exec: black_hole 192.168.x.x
 ```
