### ISSUE TITLE
[❌] 可以给prefer_ipv4 提供一个按钮.. 

### ISSUE THREAD

**Issue by ihuanx** [sbwml/luci-app-mosdns#176]
```
  # 国内解析
  - tag: local_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_local
```
