### ISSUE TITLE
IPQ6018 QSDK，启动不了/etc/init.d/mosdns

### ISSUE THREAD

**Issue by mjyhj** [sbwml/luci-app-mosdns#36]
![image](https://user-images.githubusercontent.com/22577418/205508968-95464d9f-f5a9-4133-a4f2-bf2690e59732.png)

![image](https://user-images.githubusercontent.com/22577418/205509683-d0a663d9-3d84-48f1-8352-cd8a11f9b381.png)

直接执行/usr/bin/mosdns start -c /etc/mosdns/config.yaml  是可以启动的

**Comment by sbwml** [comment]
我没有用过你说的QSDK，我也不清除它和openwrt 的区别。

但是这个mosdns luci 工作流程其实挺简单的，根据 luci 设定的参数生成创建配置文件，mosdns使用配置文件启动，就两个工作

我需要通过这些操作得到的一些信息：

1、提供 `/etc/config/mosdns` 文件内容
2、在luci 勾选启用mosdns，保存并应用 （不管它运行与否，提供 `/etc/mosdns/config.yaml` 文件内容，用格式化方式贴上来）
3、终端执行 `mosdns start -c /etc/mosdns/config.yaml`  ，把 终端输出 和 `/tmp/mosdns.log` （如果有）内容贴上来

**Comment by mjyhj** [comment]
> 

CPU是 IPQ6018，安装的是mosdns_4.5.3-1_aarch64_cortex-a53.ipk

1.
![image](https://user-images.githubusercontent.com/22577418/205720354-0c5716b2-cba7-4bf0-8685-7ab42eca3a7c.png)

2.`log:
  level: info
  file: "/tmp/mosdns.log"

include: []

data_providers:
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true

  - tag: whitelist
    file: "/etc/mosdns/rule/whitelist.txt"
    auto_reload: true

  - tag: blocklist
    file: "/etc/mosdns/rule/blocklist.txt"
    auto_reload: true

  - tag: greylist
    file: "/etc/mosdns/rule/greylist.txt"
    auto_reload: true

  - tag: hosts
    file: "/etc/mosdns/rule/hosts.txt"
    auto_reload: true

  - tag: redirect
    file: "/etc/mosdns/rule/redirect.txt"
    auto_reload: true

  - tag: local_ptr
    file: "/etc/mosdns/rule/local-ptr.txt"
    auto_reload: true

  - tag: adlist
    file: "/etc/mosdns/rule/adlist.txt"
    auto_reload: true

plugins:
  - tag: lazy_cache
    type: cache
    args:
      size: 200000
      lazy_cache_ttl: 259200

  - tag: modify_ttl
    type: ttl
    args:
      minimal_ttl: 0
      maximum_ttl: 0

  - tag: "forward_local"
    type: forward
    args:
      upstream:
        - addr: 119.29.29.29
      bootstrap:
        - "119.29.29.29"

  - tag: "forward_remote"
    type: fast_forward
    args:
      upstream:
        - addr: tls://8.8.8.8
          enable_pipeline: false

  - tag: query_is_whitelist_domain
    type: query_matcher
    args:
      domain:
        - "provider:whitelist"

  - tag: query_is_blocklist_domain
    type: query_matcher
    args:
      domain:
        - "provider:blocklist"

  - tag: query_is_greylist_domain
    type: query_matcher
    args:
      domain:
        - "provider:greylist"

  - tag: query_is_hosts_domain
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  - tag: query_is_redirect_domain
    type: redirect
    args:
      rule:
        - "provider:redirect"

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn,apple-cn,icloud,google-cn,tld-cn"

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "full:disable-category-ads-all.null"

  - tag: match_local_ptr
    type: query_matcher
    args:
      qtype: [12]
      domain:
        - "provider:local_ptr"

  - tag: match_qtype65
    type: query_matcher
    args:
      qtype: [65]

  - tag: "main_sequence"
    type: "sequence"
    args:
      exec:
        - _misc_optm
        - query_is_hosts_domain
        - query_is_redirect_domain

        - if: query_is_whitelist_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        - if: "query_is_blocklist_domain || query_is_ad_domain || match_local_ptr || match_qtype65"
          exec:
            - _new_nxdomain_response
            - _return

        - lazy_cache

        - if: query_is_greylist_domain
          exec:
            - forward_remote
            - modify_ttl
            - _return

        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
            - _return
        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
          fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":5335"
      - protocol: tcp
        addr: ":5335"
`

3.
root@OpenWrt:/tmp/upload# mosdns start -c /etc/mosdns/config.yaml
Killed
root@OpenWrt:/tmp/upload# 


![image](https://user-images.githubusercontent.com/22577418/205720762-4710a2c8-2442-439a-b200-d3c652900524.png)

**Comment by mjyhj** [comment]
方案2：使用[easymos](https://github.com/pmkol/easymosdns)上的配置

1.
![image](https://user-images.githubusercontent.com/22577418/205725852-9f80e145-9143-4e7b-9470-77faed970633.png)


2.
```
# Powered by Apad.pro
# https://apad.pro/easymosdns
#
log:
    file: "/tmp/mosdns.log"
    level: info

data_providers:
  - tag: chinalist
    file: "/etc/mosdns/rules/china_domain_list.txt"
    auto_reload: true
  - tag: gfwlist
    file: "/etc/mosdns/rules/gfw_domain_list.txt"
    auto_reload: true
  - tag: cdncn
    file: "/etc/mosdns/rules/cdn_domain_list.txt"
    auto_reload: true
  - tag: chinaip
    file: "/etc/mosdns/rules/china_ip_list.txt"
    auto_reload: true
  - tag: gfwip
    file: "/etc/mosdns/rules/gfw_ip_list.txt"
    auto_reload: true
  - tag: adlist
    file: "/etc/mosdns/rules/ad_domain_list.txt"
    auto_reload: true
  - tag: ecscn
    file: "/etc/mosdns/ecs_cn_domain.txt"
    auto_reload: true
  - tag: ecstw
    file: "/etc/mosdns/ecs_tw_domain.txt"
    auto_reload: true
  - tag: hosts
    file: "/etc/mosdns/hosts.txt"
    auto_reload: true

plugins:
  # 缓存的插件
  - tag: cache
    type: cache
    args:
      size: 102400
      redis: 'redis://192.168.123.254:6379/1'
      lazy_cache_ttl: 172800

  # Hosts的插件
  - tag: hosts
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  # 调整ECS的插件
  # [auto|global|cn|tw]
  - tag: ecs_auto
    type: ecs
    args:
      auto: true
      mask4: 24
      force_overwrite: false
  - tag: ecs_global
    type: ecs
    args:
      auto: true
      mask4: 22
      force_overwrite: false
  - tag: ecs_cn
    type: ecs
    args:
      auto: false
      ipv4: "1.2.4.0"
      ipv6: "2001:dc7:1000::1"
      mask4: 24
      force_overwrite: true
  - tag: ecs_tw
    type: ecs
    args:
      auto: false
      ipv4: "168.95.1.0"
      ipv6: "2001:b000:168::1"
      mask4: 22
      force_overwrite: true

  # 调整TTL的插件
  - tag: ttl_short
    type: ttl
    args:
      minimal_ttl: 60
      maximum_ttl: 3600
  - tag: ttl_long
    type: ttl
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  # 匹配PTR类型请求的插件
  - tag: query_is_ptr
    type: query_matcher
    args:
      qtype: [12]

  # 匹配TYPE65类型请求的插件
  - tag: qtype65
    type: query_matcher
    args:
      qtype: [65]
      
  # 屏蔽请求的插件
  - tag: black_hole
    type: blackhole
    args:
      rcode: 0
      ipv4: "127.0.0.1"
      ipv6: "::1"

  # 匹配Akamai的插件
  - tag: response_cname_akamai
    type: response_matcher
    args:
      cname:
        - "akamaiedge.net"
        - "akadns.net"
        - "edgekey.net"

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:chinalist"

  # 匹配污染域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:gfwlist"

  # 匹配CDN域名的插件
  - tag: query_is_cdn_cn_domain
    type: query_matcher
    args:
      domain:
        - "provider:cdncn"

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "provider:adlist"

  # 匹配强制本地解析域名的插件
  - tag: query_is_cn_domain
    type: query_matcher
    args:
      domain:
        - "provider:ecscn"

  # 匹配强制非本地解析域名的插件
  - tag: query_is_tw_domain
    type: query_matcher
    args:
      domain:
        - "provider:ecstw"

  # 匹配本地IP的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "provider:chinaip"

  # 匹配污染IP的插件
  - tag: response_has_gfw_ip
    type: response_matcher
    args:
      ip:
        - "provider:gfwip"

  # 转发至本地服务器的插件
  # [local|alidns|dnspod]
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "tls://120.53.53.53:853"
          enable_pipeline: true
        - addr: "udpme://223.5.5.5"
          trusted: true
  - tag: forward_alidns
    type: fast_forward
    args:
      upstream:
        - addr: "223.5.5.5"
  - tag: forward_dnspod
    type: fast_forward
    args:
      upstream:
        - addr: "tls://120.53.53.53:853"
          enable_pipeline: true

  # 转发至远程服务器的插件
  # [remote|host_socks|googledns|googledns_socks]
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: "tls://8.8.4.4:853"
          enable_pipeline: true
        - addr: "208.67.220.220:443"
  - tag: forward_host_socks
    type: fast_forward
    args:
      upstream:
        - addr: "127.0.0.1:53"
          socks5: "127.0.0.1:1080"
  - tag: forward_googledns
    type: fast_forward
    args:
      upstream:
        - addr: "tls://8.8.4.4:853"
          enable_pipeline: true
        - addr: "udpme://8.8.8.8"
          trusted: true
  - tag: forward_googledns_socks
    type: fast_forward
    args:
      upstream:
        - addr: "tcp://8.8.8.8"
          socks5: "127.0.0.1:1080"
          enable_pipeline: true

  # 转发至本地无污染服务器的插件
  # [easymosdns|tunadns]
  - tag: forward_easymosdns
    type: forward
    args:
      upstream:
        - addr: "https://doh.apad.pro/dns-query"
      bootstrap:
        - "119.29.29.29"
      timeout: 5
  - tag: forward_tunadns
    type: fast_forward
    args:
      upstream:
        - addr: "https://101.6.6.6:8443/dns-query"

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义
  # 否则 sequence 找不到对应插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 域名映射IP
        - hosts

        # 获取ECS
        #- ecs_auto

        # 缓存
        - cache

        # 屏蔽TYPE65类型请求
        - if: qtype65
          exec:
          - black_hole
          - _return

        # 强制用本地服务器解析
        - if: "(query_is_cn_domain) || [query_is_ptr]"
          exec:
            - forward_alidns
            - _return

        # 强制用非本地服务器解析
        - if: query_is_tw_domain
          exec:
            - ecs_tw
            - forward_googledns
            - ttl_long
            - _return

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
          - forward_googledns
          - _return

        # 已知的本地域名或CDN域名用本地服务器解析
        - if: "(query_is_local_domain) || (query_is_cdn_cn_domain) || (response_cname_akamai)"
          exec:
            - forward_alidns
            - _return

        # 已知的污染域名用远程服务器解析
        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - ecs_cn
            - forward_googledns
            - _return

        # 剩下的未知域名用IP分流，分流原理请参考fallback的工作流程
          # primary 从远程服务器获取应答，丢弃本地IP的结果
        - primary:
            - _prefer_ipv4
            #- ecs_global
            - forward_googledns
            - ttl_short
            - if: "(response_has_local_ip) || (response_cname_akamai)"
              exec:
                - _drop_response
          # secondary 从本地服务器获取应答
          secondary:
            # - ecs_auto
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer] || (response_has_gfw_ip)"
              exec:
                - _prefer_ipv4
                - ecs_cn
                - forward_remote
                - ttl_long
          # 如果 primary 超过这个延时还没响应，可以假设 primary 出现了问题
          # 这时会采用 secondary 应答。单位: 毫秒
          fast_fallback: 2500
          always_standby: false

servers:
  - exec: main_sequence
    timeout: 5
    listeners:
      - protocol: udp
        addr: ":5335"
      - protocol: tcp
        addr: ":5335"
      #- protocol: http
      #  addr: "127.0.0.1:9053"
      #  url_path: "/dns-query"
      #  get_user_ip_from_header: "X-Forwarded-For"
      #- protocol: tls             
      #  addr: "0.0.0.0:853"
      #  cert: "/etc/mosdns/yourdomain.cert"  # TLS 所需证书文件。
      #  key: "/etc/mosdns/yourdomain.key"    # TLS 所需密钥文件。
      #  idle_timeout: 10          # 连接复用空连接超时时间。单位: 秒。默认: 10。

#api:
#    http: "127.0.0.1:9080"

```


3.使用mosdns start -c /etc/mosdns/config.yaml 则运行成功
![image](https://user-images.githubusercontent.com/22577418/205723981-2e9364b0-583f-4fbe-8c7b-959893404a5b.png)
![image](https://user-images.githubusercontent.com/22577418/205724056-79ee67b1-49a4-40e0-9855-51f36e61f78e.png)

使用/etc/init.d/mosdns start 则启动不了
![image](https://user-images.githubusercontent.com/22577418/205725041-861b22fc-6527-4e63-a712-6e5089d6c303.png)

![image](https://user-images.githubusercontent.com/22577418/205725006-f70744cb-eea6-48fa-aad7-8b0cf2478d56.png)
