### ISSUE TITLE
logfile_path()有时会返回意外的值

### ISSUE THREAD

**Issue by leoking670** [sbwml/luci-app-mosdns#40]
[luci-app-mosdns](https://github.com/sbwml/luci-app-mosdns)/[luci-app-mosdns](https://github.com/sbwml/luci-app-mosdns/tree/master/luci-app-mosdns)/[root](https://github.com/sbwml/luci-app-mosdns/tree/master/luci-app-mosdns/root)/[usr](https://github.com/sbwml/luci-app-mosdns/tree/master/luci-app-mosdns/root/usr)/[share](https://github.com/sbwml/luci-app-mosdns/tree/master/luci-app-mosdns/root/usr/share)/[mosdns](https://github.com/sbwml/luci-app-mosdns/tree/master/luci-app-mosdns/root/usr/share/mosdns)/mosdns.sh
```shell
logfile_path() (
	configfile=$(uci -q get mosdns.config.configfile)
	if [ "$configfile" = "/etc/mosdns/config.yaml" ]; then
		uci -q get mosdns.config.logfile
	else
		[ ! -f /etc/mosdns/config_custom.yaml ] && exit 1
		cat /etc/mosdns/config_custom.yaml | grep -A 4 log | grep file | awk -F ":" '{print $2}' | sed 's/\"//g;s/ //g'
	fi
)
```
请问一下这个函数中```grep -A 4 log```取4行有什么深意吗？这似乎会导致在某些常用的config写法中，获取到意外的结果，导致启动出错。以下面为例
```yaml
log:
  level: info
  file: "/tmp/mosdns.log"

data_providers:
  - tag: somedata
    file: "/foo/bar/somedata.txt"
    auto_reload: false
```
会返回两行路径
```shell
/tmp/mosdns.log
/foo/bar/somedata.txt
```
这里是否可以优化一下呢？

**Comment by sbwml** [comment]
额。。。这个这个。。。嗯~ o(*￣▽￣*)o。。。。。当时我就担忧这种情况出现，因为配置文件根本无法做到人人统一，这个喜欢加一些注释符，那个喜欢不分行的。当时看到网上的配置文件，八九不离十都是 在 log 出现的4行内（包括注释符）所以变成现在这样~ o(*￣▽￣*)o

你这个例子举得好！

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/ea7b0dec2aa8b238750e209757422eb7166036d7 这样应该是解决了，不管怎么排版，只要是mosdns v4 配置文件应该都能读 ，除非压根就没写log 的路径 ，如果这样会非常尴尬 ，哪怕给它写个  /dev/null   也好。

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/62e204a4e43625416edc6c8b86bd065261a31fff  场景2，自定义配置不存在日志路径时的修复

**Comment by sbwml** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/fa19bb05fde826c3da9e57aca573641cc7c4f87e 场景3，格式编写兼容
```yaml
file: "/xxx.log"
file: '/xxx.log'
file: /xxx.log

or not set

```
