### ISSUE TITLE
MosDNS v5.1.3使用内置预设无法启动

### ISSUE THREAD

**Issue by MagicCheshireMeow** [sbwml/luci-app-mosdns#74]
一、之前安装过老版本MosDNS一切正常，已经尝试过卸载老版本并删除了/etc/config/mosdns和/etc/mosdns目录

二、固件为内核版本5.15.98的OpenWrt x86固件

/etc/config/mosdns内容如下
config mosdns 'config'
	option listen_port '5335'
	option geo_update_week_time '*'
	option geo_update_day_time '2'
	option redirect '1'
	option configfile '/etc/mosdns/config.yaml'
	option log_level 'info'
	option logfile '/tmp/mosdns.log'
	option cache_size '20000'
	option cache_survival_time '86400'
	option idle_timeout '30'
	option minimal_ttl '0'
	option maximum_ttl '0'
	option insecure_skip_verify '0'
	option listen_port_api '9091'
	option bootstrap_dns '119.29.29.29'
	list remote_dns 'tls://8.8.8.8'
	list remote_dns 'tls://1.1.1.1'
	option concurrent '2'
	option max_conns '4'
	option enable_pipeline '1'
	option enable_http3 '1'
	option enable_ecs_remote '0'
	option dump_file '1'
	option dump_interval '600'
	option adblock '0'
	option geo_auto_update '1'
	option custom_local_dns '0'
	option enabled '0'

/etc/mosdns/config.yaml内容如下
```yaml
log:
  level: info
  file: "/tmp/mosdns.log"

api:
  http: "0.0.0.0:9091"

include: []

plugins:
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  - tag: whitelist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/whitelist.txt"

  - tag: blocklist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklist.txt"

  - tag: greylist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"

  - tag: ddnslist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/ddnslist.txt"

  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

  - tag: redirect
    type: redirect
    args:
      files:
        - "/etc/mosdns/rule/redirect.txt"

  - tag: adlist
    type: domain_set
    args:
      files:
        - "/var/disable-ads.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/local-ptr.txt"

  - tag: sp_low
    type: domain_set
    args:
      files:
        - "/usr/share/mosdns/sp_low.tdata"

  - tag: lazy_cache
    type: cache
    args:
      size: 20000
      lazy_cache_ttl: 86400
      dump_file: /etc/mosdns/cache.dump
      dump_interval: 600

  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: 59.51.78.211
        - addr: 222.246.129.81

  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tls://8.8.8.8
          bootstrap: 119.29.29.29
          enable_pipeline: true
          max_conns: 4
          insecure_skip_verify: false
          idle_timeout: 30
          enable_http3: true
        - addr: tls://1.1.1.1
          bootstrap: 119.29.29.29
          enable_pipeline: true
          max_conns: 4
          insecure_skip_verify: false
          idle_timeout: 30
          enable_http3: true

  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 0-0

  - tag: modify_ddns_ttl
    type: sequence
    args:
      - exec: ttl 5-5

  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local

  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $modify_ddns_ttl
      - matches: "!qname $ddnslist"
        exec: $modify_ttl
      - matches: has_resp
        exec: accept

  - tag: query_is_local_ip
    type: sequence
    args:
      - exec: $local_sequence
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  - tag: query_is_remote
    type: sequence
    args:
      - exec: $remote_sequence

  - tag: fallback
    type: fallback
    args:
      primary: query_is_local_ip
      secondary: query_is_remote
      threshold: 500
      always_standby: true

  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $local_sequence

  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $local_sequence

  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $remote_sequence

  - tag: query_is_whitelist_domain
    type: sequence
    args:
      - matches: qname $whitelist
        exec: $local_sequence

  - tag: query_is_greylist_domain
    type: sequence
    args:
      - matches: qname $greylist
        exec: $remote_sequence

  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches: qname $blocklist
        exec: reject 3
      - matches: qname $adlist
        exec: reject 3
      - matches: qname $sp_low
        exec: reject 3
      - matches:
        - qtype 12
        - qname $local_ptr
        exec: reject 3
      - matches: qtype 65
        exec: reject 3

  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
        - "!qname $ddnslist"
        - "!qname $blocklist"
        - "!qname $adlist"
        - "!qname $sp_low"
        - "!qname $local_ptr"
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
```
